MODEL_CFG:
  PRETRAINED: '' # '/home/guest/ocr_exp_v2/weight/layer5_relu_MULTI_NORM_0to1_ADAM_STEP/2023-01-31_min_loss.pth'
  USE_RES: !!bool true # true # false
  SEPERABLE_FFN: !!bool true # false # true #  false ## Transformer Encoder의 FFN을 Convolution을 사용할지 말지
  PRETRAINED_OPTIM: '' # '/home/guest/ocr_exp_v2/optim/layer5_relu_MULTI_NORM_0to1_ADAM_STEP/2023-01-31.pth'
  ADAPTIVE_PE: !!bool false # true
  TPS: !!bool false # true
  BATCH_SIZE: !!int 300 # 128 # 300
  RES_IN: 32
  MAX_SEQ_LENGTH: 45 # 30 #75
  ENCODER_LAYER_NUM: !!int 5 # 6 # 5 # 6 # 5 # 12 # 5 # 12 # 12 # 5 # 2 # 4
  EMBEDDING_DIM: 512
  FEED_FORWARD_DIM: 2048
  HEAD_NUM: !!int 8
  IMG_W: 192
  IMG_H: 32 # 128
  ACTIVATION: !!str 'RELU' # 'TANH' # 'LEAKYRELU' # 'GELU' # 'TANH' 
  RGB: !!bool false

TRAIN_CFG:
  LOSS_FN: "CE" # "FOCAL" # 'SOFTCE'
  OPTIMIZER: 'ADAM' # 'SGD' # 'ADAM'
  SCHEDULER: 'STEP' # 'COSINE' # 'CYCLIC' # 
  MOMENTUM: 0.9
  LR: !!float 3e-4 # 2e-4 # 1e-4 # 1e-4 ## 3e-4 ## => 신기하게 ADAM은 1e-4 ~ 1e-5를 시작으로 잡는 것이, SGD는 0.1 ~ 0.01 정도를 시작 learning rate로 잡는 것이 효과적이다.
  DEBUG: !!bool false
  BATCH_SIZE: 300 #  128 # 300
  EPOCH: !!int 100
  EVAL_EPOCH: !!int 10
  WEIGHT_FOLDER: '/home/guest/ocr_exp_v2/weight'
  OPTIM_FOLDER: '/home/guest/ocr_exp_v2/optim'

DATA_CFG:
  CONVERTER: !!str "general" # "hangul"
  TARGET_NUM: !!bool true
  TARGET_ENG: !!bool false # true
  TARGET_BOTH: !!bool false
  ## ADD_*얘네는 Label Converter 정의하는데 필요함
  ADD_NUM: !!bool True # False
  ADD_ENG: !!bool True # False
  RATIO: !!float 1.0
  DATASET: 
  #   - 'HENDatasetV2'
    - 'HENDatasetV3'
  USE_OUTDOOR: !!bool false
  BASE_FOLDER: '/home/guest/ocr_exp_v2/data/printed_text' ## 학습을 text_recognition 폴더 내에서 시킬 것이기 때문에 
  RGB: false
  ### MEAN, STD는 0.5로 고정으로 가는게 나을 것 같다
  GRAY_MEAN: 0.0 # 0.8 # 0.0 #  0.5
  GRAY_STD: 1.0 # 0.37 # 1.0 # 0.5 
  MEAN:  [0.5,0.5,0.5] # [0.8,0.8,0.8] #  [0.0,0.0,0.0] #[0.5,0.5,0.5] 
  STD:  [0.5,0.5,0.5] # [0.37,0.37,0.37] # [1.0,1.0,1.0] # [0.5,0.5,0.5] #
  BASE_CHARACTERS: 
    - ' ' ## 공백은 종성에 무조건 있기 때문에 꼭 포함을 시켜야 한다.
    - 'ㄱ'
    - 'ㄲ'
    - 'ㄳ'
    - 'ㄴ'
    - 'ㄵ'
    - 'ㄶ'
    - 'ㄷ'
    - 'ㄸ'
    - 'ㄹ'
    - 'ㄺ'
    - 'ㄻ'
    - 'ㄼ'
    - 'ㄽ'
    - 'ㄾ'
    - 'ㄿ'
    - 'ㅀ'
    - 'ㅁ'
    - 'ㅂ'
    - 'ㅃ'
    - 'ㅄ'
    - 'ㅅ'
    - 'ㅆ'
    - 'ㅇ'
    - 'ㅈ'
    - 'ㅉ'
    - 'ㅊ'
    - 'ㅋ'
    - 'ㅌ'
    - 'ㅍ'
    - 'ㅎ'
    - 'ㅏ'
    - 'ㅐ'
    - 'ㅑ'
    - 'ㅒ'
    - 'ㅓ'
    - 'ㅔ'
    - 'ㅕ'
    - 'ㅖ'
    - 'ㅗ'
    - 'ㅘ'
    - 'ㅙ'
    - 'ㅚ'
    - 'ㅛ'
    - 'ㅜ'
    - 'ㅝ'
    - 'ㅞ'
    - 'ㅟ'
    - 'ㅠ'
    - 'ㅡ'
    - 'ㅢ'
    - 'ㅣ'

  ADD_SPECIAL: !!bool False
  MAX_LENGTH: !!int 45 # 75
  IMG_H: !!int 32
  IMG_W: !!int 192 # 128
