MODEL_CFG:
  PRETRAINED: ''
  USE_RES: !!bool true
  PRETRAINED_OPTIM: ''
  ADAPTIVE_PE: !!bool true
  BATCH_SIZE: !!int 300
  RES_IN: 32
  MAX_SEQ_LENGTH: 30 #75
  ENCODER_LAYER_NUM: !!int 2 # 5 # 12 # 4
  EMBEDDING_DIM: 512
  FEED_FORWARD_DIM: 2048
  HEAD_NUM: !!int 8
  IMG_W: 192
  IMG_H: 32 # 128
  ACTIVATION: !!str 'TANH'
  RGB: !!bool true ## Outdoor Data는 거의 무조건 RGB이미지를 사용해야 한다

TRAIN_CFG:
  DEBUG: !!bool false
  LOSS_FN: 'CE' # 'FOCAL'
  OPTIMIZER: 'ADAM'
  SCHEDULER: 'COSINE'
  MOMENTUM: 0.9
  LR: !!float 1e-4
  BATCH_SIZE: 300
  EPOCH: !!int 100
  EVAL_EPOCH: !!int 10
  WEIGHT_FOLDER: '/home/guest/ocr_exp_v2/weight'
  OPTIM_FOLDER: '/home/guest/ocr_exp_v2/optim'

DATA_CFG:
  DATASET: 'HENDatasetOutdoor'
  USE_OUTDOOR: !!bool true
  RGB: true
  MEAN: [0.5,0.1,0.4]
  STD: [0.3,0.5,0.3]
  BASE_FOLDER: '/home/guest/ocr_exp_v2/data/croped_outdoor' ## 학습을 text_recognition 폴더 내에서 시킬 것이기 때문에 
  BASE_CHARACTERS: 
    - ' ' ## 공백은 종성에 무조건 있기 때문에 꼭 포함을 시켜야 한다.
    - 'ㄱ'
    - 'ㄲ'
    - 'ㄳ'
    - 'ㄴ'
    - 'ㄵ'
    - 'ㄶ'
    - 'ㄷ'
    - 'ㄸ'
    - 'ㄹ'
    - 'ㄺ'
    - 'ㄻ'
    - 'ㄼ'
    - 'ㄽ'
    - 'ㄾ'
    - 'ㄿ'
    - 'ㅀ'
    - 'ㅁ'
    - 'ㅂ'
    - 'ㅃ'
    - 'ㅄ'
    - 'ㅅ'
    - 'ㅆ'
    - 'ㅇ'
    - 'ㅈ'
    - 'ㅉ'
    - 'ㅊ'
    - 'ㅋ'
    - 'ㅌ'
    - 'ㅍ'
    - 'ㅎ'
    - 'ㅏ'
    - 'ㅐ'
    - 'ㅑ'
    - 'ㅒ'
    - 'ㅓ'
    - 'ㅔ'
    - 'ㅕ'
    - 'ㅖ'
    - 'ㅗ'
    - 'ㅘ'
    - 'ㅙ'
    - 'ㅚ'
    - 'ㅛ'
    - 'ㅜ'
    - 'ㅝ'
    - 'ㅞ'
    - 'ㅟ'
    - 'ㅠ'
    - 'ㅡ'
    - 'ㅢ'
    - 'ㅣ'
  ADD_NUM: !!bool False
  ADD_ENG: !!bool False
  ADD_SPECIAL: !!bool False
  MAX_LENGTH: !!int 30 # 75
  IMG_H: !!int 32
  IMG_W: !!int 192 #128
